### ISSUE TITLE
Advanced compilation with chromebuild

### ISSUE THREAD

**Issue by prakhar1989** [clumsyjedi/lein-chromebuild#7]
Hey @clumsyjedi, thanks a bunch for this amazing plugin! I had a quick question about using advanced compilation to reduce the file size (currently it stands at 2.6mb). Running the following still gives me the output of the same size -
```
$ lein with-profile +prod chromebuild once
```

Here's my `project.clj`
```clojure
(defproject doubleshift "0.1.0-SNAPSHOT"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.107"]
                 [khroma "0.3.0"]
                 [reagent "0.6.0"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]]

  :plugins [[lein-cljsbuild "1.0.6"]
            [lein-chromebuild "0.3.0"]]

  :source-paths ["src"]
  :cljsbuild {:builds {:main
                       {:source-paths ["src"]
                        :compiler {:output-to "target/unpacked/doubleshift.js"
                                 :output-dir "target/js"}}}}
  :profiles {:dev {:cljsbuild
                   {:builds {:main
                     {:source-paths ["src"]
                      :compiler {:optimizations :whitespace
                                 :pretty-print true}}}}}
             :prod {:cljsbuild
                   {:builds {:main
                     {:source-paths ["src"]
                      :compiler {:optimizations :advanced
                                 :pretty-print false}}}}}})

```

Any help is appreciated.

**Comment by clumsyjedi** [comment]
Hi, thanks for the kind words.

Can you try this command instead?

```
lein with-profile +prod do clean, chromebuild once
```

This works for me with a bastardised copy of your `project.clj`. If it doesn't let me know and I will dig further.

Cheers :)

f

**Comment by prakhar1989** [comment]
Hey @clumsyjedi, thanks for getting back. I tried the command and it did minify the file (it stands at 260kb) which is awesome.

Unfortunately though the extension no longer works, and the `popup.js`, is unable to find the module and raises an `UndefinedError`. 

```javascript
doubleshift.popup.init(); // gives doubleshift is undefined
```
I even tried with the default `project.clj` that ships with the template to make sure I haven't messed up but the issue persists.

Any ideas what's wrong?

**Comment by clumsyjedi** [comment]
Yeah, the advanced compilation removes the fn name doubleshift.popup.init and replaces it with a minified fn name. To be honest I have never done advanced compilation for extensions so you are in uncharted territory a bit.

This is bug and will probably need to be patched in lein-chrome-extension at some point, which I can't really be bothered to do any time soon. There is a workaround though, if you change the sig of doubleshift.popup.init to be:

(defn ^:export init []

Then it will work. Let me know if you have any further questions.

**Comment by prakhar1989** [comment]
This works like a charm and it brought my build size down to 300kb! Thanks a ton @clumsyjedi.

> This is bug and will probably need to be patched in lein-chrome-extension at some point

If your time permits, can you provide me a few tips on how get started on this? It's the least I can do. I'd love to contribute and take a shot at fixing this.

Thanks!

**Comment by clumsyjedi** [comment]
@prakhar1989 If you're still interested then have a look at https://github.com/clumsyjedi/lein-chrome-extension/issues/6. Cheers
